
default: &default
  adapter: postgresql
  database: notes_app_<%= Rails.env %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: postgres
  password: admin

test:
  <<: *default
  username: postgres
  password: admin

production:
  <<: *default
  username: postgres
  password: admin
